# Generated by Django 5.2.17 on 2026-08-14 10:27

import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=projects.models.new_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="Untitled", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("transcribing", "Transcribing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                (
                    "source_file",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("duration", models.FloatField(default=0.0)),
                ("has_video", models.BooleanField(default=False)),
                ("video_width", models.IntegerField(default=0)),
                ("video_height", models.IntegerField(default=0)),
                ("video_fps", models.FloatField(default=0.0)),
                ("language", models.CharField(blank=True, default="", max_length=16)),
                (
                    "asr_backend",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("voice", models.JSONField(blank=True, null=True)),
                ("preview_failed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="projects_pr_created_775fe7_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Render",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=projects.models.new_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("rendering", "Rendering"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("tokens", models.JSONField(default=list)),
                ("format", models.CharField(default="wav", max_length=8)),
                ("with_video", models.BooleanField(default=False)),
                ("file", models.CharField(blank=True, default="", max_length=255)),
                ("bytes", models.BigIntegerField(default=0)),
                ("duration", models.FloatField(default=0.0)),
                ("pieces", models.IntegerField(default=0)),
                ("stats", models.JSONField(default=dict)),
                ("warnings", models.JSONField(default=list)),
                ("synthesis", models.JSONField(default=dict)),
                ("task_id", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renders",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-created_at"],
                        name="projects_re_project_450740_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("start", models.FloatField()),
                ("end", models.FloatField()),
                ("text", models.TextField(blank=True, default="")),
                ("first_word", models.IntegerField()),
                ("last_word", models.IntegerField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "index"), name="unique_segment_index"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("token_id", models.CharField(max_length=32)),
                ("text", models.CharField(max_length=255)),
                ("start", models.FloatField()),
                ("end", models.FloatField()),
                ("confidence", models.FloatField(default=1.0)),
                ("segment", models.IntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
                "indexes": [
                    models.Index(
                        fields=["project", "index"],
                        name="projects_wo_project_f5a4bb_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "index"), name="unique_word_index"
                    ),
                    models.UniqueConstraint(
                        fields=("project", "token_id"), name="unique_word_token"
                    ),
                ],
            },
        ),
    ]
