# Generated by Django 5.2.17 on 2026-08-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_translation_dubrender_voiceprofile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dubrender',
            new_name='projects_du_transla_e825d0_idx',
            old_name='projects_du_translat_idx',
        ),
    ]
