# Generated by Django 5.2.17 on 2026-08-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_projects_du_translat_idx_projects_du_transla_e825d0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='dubrender',
            name='quality',
            field=models.CharField(default='standard', max_length=16),
        ),
        migrations.AddField(
            model_name='render',
            name='quality',
            field=models.CharField(default='standard', max_length=16),
        ),
    ]
