# Generated by Django 5.2.17 on 2026-08-29 02:18

import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_dubrender_quality_render_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceModel',
            fields=[
                ('id', models.CharField(default=projects.models.new_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('rvc', 'RVC voice conversion'), ('xtts-ft', 'Fine-tuned XTTS')], default='rvc', max_length=16)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading data'), ('training', 'Training'), ('pulling', 'Pulling artifacts'), ('evaluating', 'Evaluating'), ('ready', 'Ready'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('kaggle_dataset', models.CharField(blank=True, default='', max_length=255)),
                ('kaggle_kernel', models.CharField(blank=True, default='', max_length=255)),
                ('model_file', models.CharField(blank=True, default='', max_length=255)),
                ('index_file', models.CharField(blank=True, default='', max_length=255)),
                ('metrics', models.JSONField(default=dict)),
                ('task_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_models', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='projects_vo_project_c5658b_idx')],
            },
        ),
    ]
